name: Build Binaries

permissions:
  contents: read

on:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - uses: dtolnay/rust-toolchain@stable

      - name: Install cross
        run: cargo install cross --locked

      - name: cargo build (cross)
        run: cross build --release -p shpool --target ${{ matrix.target }}

      - name: Pack binary
        run: tar -C "target/${{ matrix.target }}/release" -czvf "shpool-${{ matrix.target }}.tar.gz" shpool

      - uses: actions/upload-artifact@v5
        with:
          name: shpool-${{ matrix.target }}
          path: shpool-${{ matrix.target }}.tar.gz
          if-no-files-found: error
